// This file is automatically generated by Diesel CLI

table! {
    trades (id) {
        id -> Integer,
        trade_id -> Text,
        buyer_order_id -> Text,
        seller_order_id -> Text,
        price -> Integer,
        quantity -> Integer,
        buyer_user_id -> Integer,
        seller_user_id -> Integer,
        created_at -> Timestamp,
    }
}

table! {
    orders (id) {
        id -> Integer,
        order_id -> Text,
        user_id -> Integer,
        side -> Text,
        price -> Integer,
        quantity -> Integer,
        filled_quantity -> Integer,
        status -> Text,
        created_at -> Timestamp,
        updated_at -> Timestamp,
    }
}

table! {
    snapshots (id) {
        id -> Integer,
        snapshot_id -> Text,
        orderbook_state -> Text,
        created_at -> Timestamp,
    }
}
